- app/src/UI/Map.tsx
- app/src/state/reducers/MooseSightings.ts
- Fixing reducer logic to update mooseArray & fixing string comparison for logos
> Reducer Fix

- app/index.html
- app/todo.txt
- Add attribution for moose images
- Edit todo
> attribution

- app/src/UI/Map.tsx
- Fixing age comparison to work with new enum
- change offset to be based on pixels
> fix icon offset

- app/src/UI/Footer.css
- app/src/UI/Footer.tsx
- app/src/UI/Form.css
Styling changes and added privacy link
> styled form buttons, privacy link

- app/todo.txt
- update readme and package.json to test for android build
- Very basic input validation
- Fix: moose location attribute
- snackbar early wip
- snackbar message displaying
- green meese
- styled form buttons, privacy link
- created popup
- added date format
- update todo feb22
> update todo feb22

- api/src/Db/db.ts
- app/src/UI/Sightings.tsx
- app/src/state/reducers/MooseSightings.ts
- app/src/state/sagas/mooseSightingsSaga.ts
- Updated sightings to not use hardcoded values and for the database to not save duplicate sightings
> Sync Moose Updates

- app/src/App.tsx
- app/src/UI/Header.css
- app/src/UI/Header.tsx
- app/todo.txt
Reverts bcgov/MooseTrackerV2#41
> Revert "Fix/route indication"

- api/Dockerfile
- api/openshift_build_config.yml
- api/openshift_deploy_config.yml
- api/package-lock.json
- build config for api
- deploy config for api
> Beginnings of pipeline

- app/src/UI/About.css
- app/src/UI/About.tsx
> About Page Update

- README.md
- app/android/app/capacitor.build.gradle
- app/android/capacitor.settings.gradle
- app/capacitor.config.ts
- app/ios/App/App.xcodeproj/project.pbxproj
- app/ios/App/App/Info.plist
- app/ios/App/Podfile
- app/ios/App/Podfile.lock
- app/package-lock.json
- app/package.json
- app/src/UI/Header.css
- app/src/UI/Header.tsx
- app/src/UI/Map.tsx
- app/src/state/sagas/mooseSightingsSaga.ts
Set up with xcode and testflight, made changes to map location panning to the marker location.
> Ios test setup

- api/src/index.ts
- api/src/paths/recordSightings.ts
- Updating API call to await response in case of errors
> False Positive Response Fix

- app/src/UI/Map.tsx
- app/src/UI/featureStylers.ts
- app/vite.config.js
- app/vite.config.ts
map layer added to show management areas with outlines and labels
> add local mgmt features & labels

- api/src/interfaces.ts
- app/src/UI/About.css
- app/src/UI/About.tsx
- app/src/UI/Form.css
- app/src/UI/Form.tsx
- app/src/UI/Regs.css
- app/src/UI/Sightings.css
- app/src/UI/Sightings.tsx
- app/src/state/reducers/MooseSightings.ts
- app/src/state/sagas/mooseSightingsSaga.ts
Added validation for form inputs, corrected errors when multiple, removed modal, changed text wording on the form, edited styling
> Form Validation Changes

- app/src/App.css
- app/src/App.tsx
- app/src/UI/About.tsx
- app/src/UI/Footer.css
- app/src/UI/Header.css
- app/src/UI/Header.tsx
- app/src/UI/Map.css
- Moved map to new page named map
- removed map from sightings and add moose
> 102 newmappage

- app/src/state/sagas/mooseSightingsSaga.ts
There were duplicate sightings being written to the database, this takes care of that
> Filter out already synced sightings

- app/src/UI/About.css
- app/src/UI/Footer.css
- app/src/UI/Footer.tsx
- app/src/UI/Form.css
- app/src/UI/Form.tsx
- app/src/UI/Header.css
- app/src/UI/Header.tsx
- app/src/UI/Map.css
- app/src/UI/Regs.css
- app/src/UI/Regs.tsx
- app/src/UI/Sightings.css
- package-lock.json
- package.json
Changes to css for mobile optimization and a small change to regs so full regs on page load
> 103 cssheight

- api/src/Db/db.ts
- api/src/interfaces.ts
- app/src/state/sagas/mooseSightingsSaga.ts
Reverts bcgov/MooseTrackerV2#107
> Revert "Typing"

- api/package-lock.json
- api/package.json
- api/src/Db/db.ts
- api/src/interfaces.ts
- api/src/paths/recordSightings.ts
- app/src/state/sagas/mooseSightingsSaga.ts
- Includes cow/bull/calf/unknown counts, hoursOut, date
- Removes dateFrom, dateTo, mooseCount
- Uses sql-template-strings instead of manual insertion strings
> API & DB Updates

- app/src/state/reducers/MooseSightings.ts
0 was being evaluated as falsey
> Change moose counts back to zero

- app/capacitor.config.ts
- app/src/state/sagas/mooseSightingsSaga.ts
https://capacitorjs.com/docs/apis/http
> Use capacitorhttp.post

- app/android/app/build.gradle
Bump up `versionCode` and `versionName` in the Android build.gradle
> Bump up android versionCode and versionName
